# Generated by Django 4.2.13 on 2024-06-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_created_at_news_created_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterField(
            model_name='news',
            name='created_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
